import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./Provider/ReactQueryProvider";
import dynamic from "next/dynamic";
import ThemeToggle from "./components/ThemeToggle";

// const ThemeToggle = dynamic(() => import("./components/ThemeToggle"), {
//   ssr: false,
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NPM Filter Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <body className="bg-white dark:bg-slate-500">
        <ThemeToggle />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
